apiVersion: v1
data:
  resolvfix.sh: |
    #!/bin/bash
    interface=$(grep -vE "lo:|face|Inter" /proc/net/dev | sort -n -k 2 | tail -1 | awk '{ sub (":", "", $1); print $1 }')
    ipaddr=$(ip -4 -o a s $interface | grep "scope global" | awk '{ sub ("/..", "", $4); print $4 }')
    cat > /etc/resolv.conf << EOF
    search ceph.svc.cluster.local
    nameserver $ipaddr
    EOF

    exec /entrypoint.sh
kind: ConfigMap
metadata:
  name: resolvescript
  namespace: rook-ceph
